# Generated by Django 3.2 on 2021-05-24 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadposts',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 22, 31, 59, 369635)),
        ),
    ]
