# Generated by Django 3.2 on 2021-05-24 17:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0002_threadposts_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadposts',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 22, 35, 14, 821197)),
        ),
        migrations.AlterField(
            model_name='threadposts',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
